name = "ApproxFunRational"
uuid = "3d0dae4a-d0ce-400f-add5-31ee3cccaa25"
authors = ["Tom Trogdon"]
version = "0.1.0"

[compat]
julia = "0.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
